name: clickcart
description: E-Commerce App built in flutter using GetX


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  get: ^4.6.6   #for page routing and show snack-bar
  bottom_navy_bar: ^6.0.0   #for show beautiful bottom animation navigation  bar
  smooth_page_indicator: ^1.1.0   #for animate the CarouselSlider product image slider
  flutter_rating_bar: ^4.0.1    #for show start rating
  font_awesome_flutter: ^10.7.0   #for use icons
  animations: ^2.0.11   #for animation
  provider: ^6.1.2    #for state-management
  dropdown_button2: ^2.3.9    #for dropdown
  flutter_cart: ^0.0.9    #for handle cart easly
  get_storage: ^2.1.1   #to store local data like shared preference
  flutter_login: ^5.0.0   #for login and registe UI
  webview_flutter: ^4.7.0   #to open web-view for tracking page
  flutter_stripe: ^10.1.1   #for payment internation
  onesignal_flutter: ^5.1.6   #fro send notification
  web3dart: ^2.7.3
  http: ^1.2.1
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  adaptive_icon_background : "#ffffff"
  adaptive_icon_foreground : "assets/images/logo.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
